#! /bin/sh

if ! which dch >/dev/null; then
	echo >&2 "please install devscripts"
	exit 1
fi

if ! which debootstrap >/dev/null; then
	echo >&2 "please install debootstrap"
	exit 1
fi

# rm -f *-amd64 *-arm64
exec germinate-update-metapackage --vcs
rm -f *.old
